"""Added columns.

Revision ID: 3718a1374f61
Revises: fd4a5edefd09
Create Date: 2025-10-26 06:58:53.358626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3718a1374f61'
down_revision: Union[str, Sequence[str], None] = 'fd4a5edefd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_contents_category'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_keyword'), table_name='generated_contents')
    op.drop_table('generated_contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_contents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_contents_pkey'))
    )
    op.create_index(op.f('ix_generated_contents_keyword'), 'generated_contents', ['keyword'], unique=False)
    op.create_index(op.f('ix_generated_contents_id'), 'generated_contents', ['id'], unique=False)
    op.create_index(op.f('ix_generated_contents_category'), 'generated_contents', ['category'], unique=False)
    # ### end Alembic commands ###
