"""create table

Revision ID: 5d020f477842
Revises: 3718a1374f61
Create Date: 2025-10-26 15:00:02.389392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d020f477842'
down_revision: Union[str, Sequence[str], None] = '3718a1374f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('keyword', sa.String(), nullable=True),
        sa.Column('category_large', sa.String(), nullable=True),
        sa.Column('category_medium', sa.String(), nullable=True),
        sa.Column('category_small', sa.String(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        # onupdate は DB トリガーが必要なため、create_table からは削除（カラム自体は作成）
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), 
        sa.PrimaryKeyConstraint('id')
    )
    
    # インデックス名をテーブル名に合わせ、カラム名のタイポを修正
    op.create_index(op.f('ix_generation_history_category_large'), 'generation_history', ['category_large'], unique=False)
    op.create_index(op.f('ix_generation_history_keyword'), 'generation_history', ['keyword'], unique=False)
    
    # id への冗長なインデックスは削除
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # upgrade と逆の操作を記述
    op.drop_index(op.f('ix_generation_history_keyword'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_category_large'), table_name='generation_history')
    op.drop_table('generation_history')
    # ### end Alembic commands ###