"""create from scratch

Revision ID: e6ea98ab93fe
Revises: f58be067ab53
Create Date: 2025-11-01 05:38:50.404337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6ea98ab93fe'
down_revision: Union[str, Sequence[str], None] = 'f58be067ab53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generation_history', 
                    'keyword',  # 変更前のカラム名
                    new_column_name='term',  # 変更後のカラム名
                    existing_type=sa.VARCHAR(), # 既存の型を指定
                    autoincrement=False, 
                    nullable=True
                    )
    op.drop_index(op.f('ix_generation_history_category_large'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_keyword'), table_name='generation_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_large', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_medium', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_small', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('generation_history_pkey'))
    )
    op.create_index(op.f('ix_generation_history_keyword'), 'generation_history', ['keyword'], unique=False)
    op.create_index(op.f('ix_generation_history_category_large'), 'generation_history', ['category_large'], unique=False)
    # ### end Alembic commands ###
