"""create from scratch

Revision ID: f58be067ab53
Revises: 5d020f477842
Create Date: 2025-11-01 05:11:33.936758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58be067ab53'
down_revision: Union[str, Sequence[str], None] = '5d020f477842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('keyword', sa.String(), nullable=True),
        sa.Column('category_large', sa.String(), nullable=True),
        sa.Column('category_medium', sa.String(), nullable=True),
        sa.Column('category_small', sa.String(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        # onupdate は DB トリガーが必要なため、create_table からは削除（カラム自体は作成）
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), 
        sa.PrimaryKeyConstraint('id')
    )
    
    # インデックス名をテーブル名に合わせ、カラム名のタイポを修正
    op.create_index(op.f('ix_generation_history_category_large'), 'generation_history', ['category_large'], unique=False)
    op.create_index(op.f('ix_generation_history_keyword'), 'generation_history', ['keyword'], unique=False)
    
    # id への冗長なインデックスは削除
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
