"""create table

Revision ID: fd4a5edefd09
Revises: 4bacb7b063da
Create Date: 2025-10-11 18:03:01.580238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4a5edefd09'
down_revision: Union[str, Sequence[str], None] = '4bacb7b063da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_contents_category'), 'generated_contents', ['category'], unique=False)
    op.create_index(op.f('ix_generated_contents_id'), 'generated_contents', ['id'], unique=False)
    op.create_index(op.f('ix_generated_contents_keyword'), 'generated_contents', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_contents_keyword'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_category'), table_name='generated_contents')
    op.drop_table('generated_contents')
    # ### end Alembic commands ###
